// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubeport/v1/daemon.proto

package kubeportv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardState int32

const (
	ForwardState_FORWARD_STATE_UNSPECIFIED ForwardState = 0
	ForwardState_FORWARD_STATE_STARTING    ForwardState = 1
	ForwardState_FORWARD_STATE_RUNNING     ForwardState = 2
	ForwardState_FORWARD_STATE_FAILED      ForwardState = 3
	ForwardState_FORWARD_STATE_STOPPED     ForwardState = 4
	ForwardState_FORWARD_STATE_WAITING     ForwardState = 5 // lazy mode: local port bound, SPDY tunnel not yet open
)

// Enum value maps for ForwardState.
var (
	ForwardState_name = map[int32]string{
		0: "FORWARD_STATE_UNSPECIFIED",
		1: "FORWARD_STATE_STARTING",
		2: "FORWARD_STATE_RUNNING",
		3: "FORWARD_STATE_FAILED",
		4: "FORWARD_STATE_STOPPED",
		5: "FORWARD_STATE_WAITING",
	}
	ForwardState_value = map[string]int32{
		"FORWARD_STATE_UNSPECIFIED": 0,
		"FORWARD_STATE_STARTING":    1,
		"FORWARD_STATE_RUNNING":     2,
		"FORWARD_STATE_FAILED":      3,
		"FORWARD_STATE_STOPPED":     4,
		"FORWARD_STATE_WAITING":     5,
	}
)

func (x ForwardState) Enum() *ForwardState {
	p := new(ForwardState)
	*p = x
	return p
}

func (x ForwardState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForwardState) Descriptor() protoreflect.EnumDescriptor {
	return file_kubeport_v1_daemon_proto_enumTypes[0].Descriptor()
}

func (ForwardState) Type() protoreflect.EnumType {
	return &file_kubeport_v1_daemon_proto_enumTypes[0]
}

func (x ForwardState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForwardState.Descriptor instead.
func (ForwardState) EnumDescriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{0}
}

// ChaosPreset selects a named chaos profile. When set, preset params
// override any inline fields in UpdateChaosRequest.
type ChaosPreset int32

const (
	ChaosPreset_CHAOS_PRESET_UNSPECIFIED      ChaosPreset = 0
	ChaosPreset_CHAOS_PRESET_SLOW_NETWORK     ChaosPreset = 1 // 200 ms spikes, 10% probability
	ChaosPreset_CHAOS_PRESET_UNSTABLE_CLUSTER ChaosPreset = 2 // 5% errors, 5% spike prob, 2 s spikes
	ChaosPreset_CHAOS_PRESET_PACKET_LOSS      ChaosPreset = 3 // 15% error rate
)

// Enum value maps for ChaosPreset.
var (
	ChaosPreset_name = map[int32]string{
		0: "CHAOS_PRESET_UNSPECIFIED",
		1: "CHAOS_PRESET_SLOW_NETWORK",
		2: "CHAOS_PRESET_UNSTABLE_CLUSTER",
		3: "CHAOS_PRESET_PACKET_LOSS",
	}
	ChaosPreset_value = map[string]int32{
		"CHAOS_PRESET_UNSPECIFIED":      0,
		"CHAOS_PRESET_SLOW_NETWORK":     1,
		"CHAOS_PRESET_UNSTABLE_CLUSTER": 2,
		"CHAOS_PRESET_PACKET_LOSS":      3,
	}
)

func (x ChaosPreset) Enum() *ChaosPreset {
	p := new(ChaosPreset)
	*p = x
	return p
}

func (x ChaosPreset) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChaosPreset) Descriptor() protoreflect.EnumDescriptor {
	return file_kubeport_v1_daemon_proto_enumTypes[1].Descriptor()
}

func (ChaosPreset) Type() protoreflect.EnumType {
	return &file_kubeport_v1_daemon_proto_enumTypes[1]
}

func (x ChaosPreset) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChaosPreset.Descriptor instead.
func (ChaosPreset) EnumDescriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{1}
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Pod           string                 `protobuf:"bytes,3,opt,name=pod,proto3" json:"pod,omitempty"`
	LocalPort     int32                  `protobuf:"varint,4,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RemotePort    int32                  `protobuf:"varint,5,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	Namespace     string                 `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ParentName    string                 `protobuf:"bytes,7,opt,name=parent_name,json=parentName,proto3" json:"parent_name,omitempty"` // non-empty for multi-port expanded forwards
	PortName      string                 `protobuf:"bytes,8,opt,name=port_name,json=portName,proto3" json:"port_name,omitempty"`       // Kubernetes port name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ServiceInfo) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *ServiceInfo) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *ServiceInfo) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *ServiceInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServiceInfo) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

func (x *ServiceInfo) GetPortName() string {
	if x != nil {
		return x.PortName
	}
	return ""
}

type PortSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	All             bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	PortNames       []string               `protobuf:"bytes,2,rep,name=port_names,json=portNames,proto3" json:"port_names,omitempty"`
	ExcludePorts    []string               `protobuf:"bytes,3,rep,name=exclude_ports,json=excludePorts,proto3" json:"exclude_ports,omitempty"`
	LocalPortOffset int32                  `protobuf:"varint,4,opt,name=local_port_offset,json=localPortOffset,proto3" json:"local_port_offset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PortSpec) Reset() {
	*x = PortSpec{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortSpec) ProtoMessage() {}

func (x *PortSpec) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortSpec.ProtoReflect.Descriptor instead.
func (*PortSpec) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *PortSpec) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *PortSpec) GetPortNames() []string {
	if x != nil {
		return x.PortNames
	}
	return nil
}

func (x *PortSpec) GetExcludePorts() []string {
	if x != nil {
		return x.ExcludePorts
	}
	return nil
}

func (x *PortSpec) GetLocalPortOffset() int32 {
	if x != nil {
		return x.LocalPortOffset
	}
	return 0
}

type ForwardStatusProto struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Service               *ServiceInfo           `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	State                 ForwardState           `protobuf:"varint,2,opt,name=state,proto3,enum=kubeport.v1.ForwardState" json:"state,omitempty"`
	Error                 string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Restarts              int32                  `protobuf:"varint,4,opt,name=restarts,proto3" json:"restarts,omitempty"`
	LastStart             *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_start,json=lastStart,proto3" json:"last_start,omitempty"`
	Connected             bool                   `protobuf:"varint,6,opt,name=connected,proto3" json:"connected,omitempty"`
	ActualPort            int32                  `protobuf:"varint,7,opt,name=actual_port,json=actualPort,proto3" json:"actual_port,omitempty"`
	NextRetry             *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=next_retry,json=nextRetry,proto3" json:"next_retry,omitempty"`
	BytesIn               int64                  `protobuf:"varint,9,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`                                               // Total bytes received from the remote side
	BytesOut              int64                  `protobuf:"varint,10,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`                                           // Total bytes sent to the remote side
	EffectiveLatencyMs    int64                  `protobuf:"varint,11,opt,name=effective_latency_ms,json=effectiveLatencyMs,proto3" json:"effective_latency_ms,omitempty"`           // Injected latency in milliseconds (0 = none)
	EffectiveJitterMs     int64                  `protobuf:"varint,12,opt,name=effective_jitter_ms,json=effectiveJitterMs,proto3" json:"effective_jitter_ms,omitempty"`              // Jitter range in milliseconds (0 = none)
	EffectiveBandwidth    int64                  `protobuf:"varint,13,opt,name=effective_bandwidth,json=effectiveBandwidth,proto3" json:"effective_bandwidth,omitempty"`             // Bandwidth cap in bytes/sec (0 = none)
	ChaosEnabled          bool                   `protobuf:"varint,14,opt,name=chaos_enabled,json=chaosEnabled,proto3" json:"chaos_enabled,omitempty"`                               // Whether chaos injection is active
	ChaosErrorRate        float64                `protobuf:"fixed64,15,opt,name=chaos_error_rate,json=chaosErrorRate,proto3" json:"chaos_error_rate,omitempty"`                      // Configured error rate (0.0-1.0)
	ChaosSpikeProbability float64                `protobuf:"fixed64,16,opt,name=chaos_spike_probability,json=chaosSpikeProbability,proto3" json:"chaos_spike_probability,omitempty"` // Latency spike probability (0.0-1.0)
	ChaosSpikeDurationMs  int64                  `protobuf:"varint,17,opt,name=chaos_spike_duration_ms,json=chaosSpikeDurationMs,proto3" json:"chaos_spike_duration_ms,omitempty"`   // Latency spike duration in ms
	ChaosErrorsInjected   int64                  `protobuf:"varint,18,opt,name=chaos_errors_injected,json=chaosErrorsInjected,proto3" json:"chaos_errors_injected,omitempty"`        // Count of errors injected so far
	ChaosSpikesInjected   int64                  `protobuf:"varint,19,opt,name=chaos_spikes_injected,json=chaosSpikesInjected,proto3" json:"chaos_spikes_injected,omitempty"`        // Count of latency spikes injected so far
	ConnBytesIn           int64                  `protobuf:"varint,20,opt,name=conn_bytes_in,json=connBytesIn,proto3" json:"conn_bytes_in,omitempty"`                                // Bytes received since last reconnect
	ConnBytesOut          int64                  `protobuf:"varint,21,opt,name=conn_bytes_out,json=connBytesOut,proto3" json:"conn_bytes_out,omitempty"`                             // Bytes sent since last reconnect
	Lazy                  bool                   `protobuf:"varint,22,opt,name=lazy,proto3" json:"lazy,omitempty"`                                                                   // true when service is configured in lazy mode
	TunnelOpen            bool                   `protobuf:"varint,23,opt,name=tunnel_open,json=tunnelOpen,proto3" json:"tunnel_open,omitempty"`                                     // lazy mode: true when the SPDY tunnel is currently open
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ForwardStatusProto) Reset() {
	*x = ForwardStatusProto{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardStatusProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardStatusProto) ProtoMessage() {}

func (x *ForwardStatusProto) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardStatusProto.ProtoReflect.Descriptor instead.
func (*ForwardStatusProto) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *ForwardStatusProto) GetService() *ServiceInfo {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ForwardStatusProto) GetState() ForwardState {
	if x != nil {
		return x.State
	}
	return ForwardState_FORWARD_STATE_UNSPECIFIED
}

func (x *ForwardStatusProto) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ForwardStatusProto) GetRestarts() int32 {
	if x != nil {
		return x.Restarts
	}
	return 0
}

func (x *ForwardStatusProto) GetLastStart() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStart
	}
	return nil
}

func (x *ForwardStatusProto) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *ForwardStatusProto) GetActualPort() int32 {
	if x != nil {
		return x.ActualPort
	}
	return 0
}

func (x *ForwardStatusProto) GetNextRetry() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRetry
	}
	return nil
}

func (x *ForwardStatusProto) GetBytesIn() int64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *ForwardStatusProto) GetBytesOut() int64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *ForwardStatusProto) GetEffectiveLatencyMs() int64 {
	if x != nil {
		return x.EffectiveLatencyMs
	}
	return 0
}

func (x *ForwardStatusProto) GetEffectiveJitterMs() int64 {
	if x != nil {
		return x.EffectiveJitterMs
	}
	return 0
}

func (x *ForwardStatusProto) GetEffectiveBandwidth() int64 {
	if x != nil {
		return x.EffectiveBandwidth
	}
	return 0
}

func (x *ForwardStatusProto) GetChaosEnabled() bool {
	if x != nil {
		return x.ChaosEnabled
	}
	return false
}

func (x *ForwardStatusProto) GetChaosErrorRate() float64 {
	if x != nil {
		return x.ChaosErrorRate
	}
	return 0
}

func (x *ForwardStatusProto) GetChaosSpikeProbability() float64 {
	if x != nil {
		return x.ChaosSpikeProbability
	}
	return 0
}

func (x *ForwardStatusProto) GetChaosSpikeDurationMs() int64 {
	if x != nil {
		return x.ChaosSpikeDurationMs
	}
	return 0
}

func (x *ForwardStatusProto) GetChaosErrorsInjected() int64 {
	if x != nil {
		return x.ChaosErrorsInjected
	}
	return 0
}

func (x *ForwardStatusProto) GetChaosSpikesInjected() int64 {
	if x != nil {
		return x.ChaosSpikesInjected
	}
	return 0
}

func (x *ForwardStatusProto) GetConnBytesIn() int64 {
	if x != nil {
		return x.ConnBytesIn
	}
	return 0
}

func (x *ForwardStatusProto) GetConnBytesOut() int64 {
	if x != nil {
		return x.ConnBytesOut
	}
	return 0
}

func (x *ForwardStatusProto) GetLazy() bool {
	if x != nil {
		return x.Lazy
	}
	return false
}

func (x *ForwardStatusProto) GetTunnelOpen() bool {
	if x != nil {
		return x.TunnelOpen
	}
	return false
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{3}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Forwards      []*ForwardStatusProto  `protobuf:"bytes,3,rep,name=forwards,proto3" json:"forwards,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *StatusResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *StatusResponse) GetForwards() []*ForwardStatusProto {
	if x != nil {
		return x.Forwards
	}
	return nil
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{5}
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceInfo           `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Persist       bool                   `protobuf:"varint,2,opt,name=persist,proto3" json:"persist,omitempty"`
	Ports         *PortSpec              `protobuf:"bytes,3,opt,name=ports,proto3" json:"ports,omitempty"` // if set, multi-port mode
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddServiceRequest) Reset() {
	*x = AddServiceRequest{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServiceRequest) ProtoMessage() {}

func (x *AddServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServiceRequest.ProtoReflect.Descriptor instead.
func (*AddServiceRequest) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *AddServiceRequest) GetService() *ServiceInfo {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *AddServiceRequest) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

func (x *AddServiceRequest) GetPorts() *PortSpec {
	if x != nil {
		return x.Ports
	}
	return nil
}

type AddServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ActualPort    int32                  `protobuf:"varint,3,opt,name=actual_port,json=actualPort,proto3" json:"actual_port,omitempty"`           // legacy single-port
	ActualPorts   []int32                `protobuf:"varint,4,rep,packed,name=actual_ports,json=actualPorts,proto3" json:"actual_ports,omitempty"` // multi-port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddServiceResponse) Reset() {
	*x = AddServiceResponse{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServiceResponse) ProtoMessage() {}

func (x *AddServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServiceResponse.ProtoReflect.Descriptor instead.
func (*AddServiceResponse) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *AddServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddServiceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AddServiceResponse) GetActualPort() int32 {
	if x != nil {
		return x.ActualPort
	}
	return 0
}

func (x *AddServiceResponse) GetActualPorts() []int32 {
	if x != nil {
		return x.ActualPorts
	}
	return nil
}

type RemoveServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Persist       bool                   `protobuf:"varint,2,opt,name=persist,proto3" json:"persist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveServiceRequest) Reset() {
	*x = RemoveServiceRequest{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServiceRequest) ProtoMessage() {}

func (x *RemoveServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServiceRequest.ProtoReflect.Descriptor instead.
func (*RemoveServiceRequest) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoveServiceRequest) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

type RemoveServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveServiceResponse) Reset() {
	*x = RemoveServiceResponse{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServiceResponse) ProtoMessage() {}

func (x *RemoveServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServiceResponse.ProtoReflect.Descriptor instead.
func (*RemoveServiceResponse) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveServiceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{11}
}

type ReloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Added         int32                  `protobuf:"varint,3,opt,name=added,proto3" json:"added,omitempty"`
	Removed       int32                  `protobuf:"varint,4,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadResponse) Reset() {
	*x = ReloadResponse{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadResponse) ProtoMessage() {}

func (x *ReloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadResponse.ProtoReflect.Descriptor instead.
func (*ReloadResponse) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *ReloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReloadResponse) GetAdded() int32 {
	if x != nil {
		return x.Added
	}
	return 0
}

func (x *ReloadResponse) GetRemoved() int32 {
	if x != nil {
		return x.Removed
	}
	return 0
}

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceInfo         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Merge         bool                   `protobuf:"varint,2,opt,name=merge,proto3" json:"merge,omitempty"` // reserved for future replace semantics; currently always additive
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *ApplyRequest) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ApplyRequest) GetMerge() bool {
	if x != nil {
		return x.Merge
	}
	return false
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Added         int32                  `protobuf:"varint,3,opt,name=added,proto3" json:"added,omitempty"`
	Skipped       int32                  `protobuf:"varint,4,opt,name=skipped,proto3" json:"skipped,omitempty"`
	Warnings      []string               `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *ApplyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ApplyResponse) GetAdded() int32 {
	if x != nil {
		return x.Added
	}
	return 0
}

func (x *ApplyResponse) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

func (x *ApplyResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type AddressMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InternalAddr  string                 `protobuf:"bytes,1,opt,name=internal_addr,json=internalAddr,proto3" json:"internal_addr,omitempty"` // K8s internal address (e.g., "web-api.demo.svc.cluster.local:80")
	LocalAddr     string                 `protobuf:"bytes,2,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`          // Local address (e.g., "localhost:8080")
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`    // kubeport service name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressMapping) Reset() {
	*x = AddressMapping{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressMapping) ProtoMessage() {}

func (x *AddressMapping) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressMapping.ProtoReflect.Descriptor instead.
func (*AddressMapping) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *AddressMapping) GetInternalAddr() string {
	if x != nil {
		return x.InternalAddr
	}
	return ""
}

func (x *AddressMapping) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *AddressMapping) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// UpdateChaosRequest mutates live chaos parameters for one or more services
// without requiring a config reload or reconnect.
type UpdateChaosRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Services []string               `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`                           // service names to update; empty = all forwards
	Preset   ChaosPreset            `protobuf:"varint,2,opt,name=preset,proto3,enum=kubeport.v1.ChaosPreset" json:"preset,omitempty"` // named preset (takes precedence when non-zero)
	// Inline params — used when preset = UNSPECIFIED.
	Enabled          bool    `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ErrorRate        float64 `protobuf:"fixed64,4,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	SpikeProbability float64 `protobuf:"fixed64,5,opt,name=spike_probability,json=spikeProbability,proto3" json:"spike_probability,omitempty"`
	SpikeDurationMs  int64   `protobuf:"varint,6,opt,name=spike_duration_ms,json=spikeDurationMs,proto3" json:"spike_duration_ms,omitempty"`
	Reset_           bool    `protobuf:"varint,7,opt,name=reset,proto3" json:"reset,omitempty"` // true = revert to config-defined chaos for named services
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateChaosRequest) Reset() {
	*x = UpdateChaosRequest{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChaosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChaosRequest) ProtoMessage() {}

func (x *UpdateChaosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChaosRequest.ProtoReflect.Descriptor instead.
func (*UpdateChaosRequest) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateChaosRequest) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *UpdateChaosRequest) GetPreset() ChaosPreset {
	if x != nil {
		return x.Preset
	}
	return ChaosPreset_CHAOS_PRESET_UNSPECIFIED
}

func (x *UpdateChaosRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateChaosRequest) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *UpdateChaosRequest) GetSpikeProbability() float64 {
	if x != nil {
		return x.SpikeProbability
	}
	return 0
}

func (x *UpdateChaosRequest) GetSpikeDurationMs() int64 {
	if x != nil {
		return x.SpikeDurationMs
	}
	return 0
}

func (x *UpdateChaosRequest) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

type UpdateChaosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       []string               `protobuf:"bytes,1,rep,name=updated,proto3" json:"updated,omitempty"`                   // names of services successfully updated
	NotFound      []string               `protobuf:"bytes,2,rep,name=not_found,json=notFound,proto3" json:"not_found,omitempty"` // names that were not recognised
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChaosResponse) Reset() {
	*x = UpdateChaosResponse{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChaosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChaosResponse) ProtoMessage() {}

func (x *UpdateChaosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChaosResponse.ProtoReflect.Descriptor instead.
func (*UpdateChaosResponse) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateChaosResponse) GetUpdated() []string {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *UpdateChaosResponse) GetNotFound() []string {
	if x != nil {
		return x.NotFound
	}
	return nil
}

type MappingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterDomain string                 `protobuf:"bytes,1,opt,name=cluster_domain,json=clusterDomain,proto3" json:"cluster_domain,omitempty"` // Custom cluster domain (default: "cluster.local")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappingsRequest) Reset() {
	*x = MappingsRequest{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingsRequest) ProtoMessage() {}

func (x *MappingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingsRequest.ProtoReflect.Descriptor instead.
func (*MappingsRequest) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{18}
}

func (x *MappingsRequest) GetClusterDomain() string {
	if x != nil {
		return x.ClusterDomain
	}
	return ""
}

type MappingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addrs         map[string]string      `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Flat map: internal addr -> local addr
	Mappings      []*AddressMapping      `protobuf:"bytes,2,rep,name=mappings,proto3" json:"mappings,omitempty"`                                                                     // Structured mappings with metadata
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MappingsResponse) Reset() {
	*x = MappingsResponse{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MappingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MappingsResponse) ProtoMessage() {}

func (x *MappingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MappingsResponse.ProtoReflect.Descriptor instead.
func (*MappingsResponse) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{19}
}

func (x *MappingsResponse) GetAddrs() map[string]string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *MappingsResponse) GetMappings() []*AddressMapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

func (x *MappingsResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *MappingsResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_kubeport_v1_daemon_proto protoreflect.FileDescriptor

const file_kubeport_v1_daemon_proto_rawDesc = "" +
	"\n" +
	"\x18kubeport/v1/daemon.proto\x12\vkubeport.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x01\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x10\n" +
	"\x03pod\x18\x03 \x01(\tR\x03pod\x12\x1d\n" +
	"\n" +
	"local_port\x18\x04 \x01(\x05R\tlocalPort\x12\x1f\n" +
	"\vremote_port\x18\x05 \x01(\x05R\n" +
	"remotePort\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vparent_name\x18\a \x01(\tR\n" +
	"parentName\x12\x1b\n" +
	"\tport_name\x18\b \x01(\tR\bportName\"\x8c\x01\n" +
	"\bPortSpec\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x1d\n" +
	"\n" +
	"port_names\x18\x02 \x03(\tR\tportNames\x12#\n" +
	"\rexclude_ports\x18\x03 \x03(\tR\fexcludePorts\x12*\n" +
	"\x11local_port_offset\x18\x04 \x01(\x05R\x0flocalPortOffset\"\xd0\a\n" +
	"\x12ForwardStatusProto\x122\n" +
	"\aservice\x18\x01 \x01(\v2\x18.kubeport.v1.ServiceInfoR\aservice\x12/\n" +
	"\x05state\x18\x02 \x01(\x0e2\x19.kubeport.v1.ForwardStateR\x05state\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1a\n" +
	"\brestarts\x18\x04 \x01(\x05R\brestarts\x129\n" +
	"\n" +
	"last_start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tlastStart\x12\x1c\n" +
	"\tconnected\x18\x06 \x01(\bR\tconnected\x12\x1f\n" +
	"\vactual_port\x18\a \x01(\x05R\n" +
	"actualPort\x129\n" +
	"\n" +
	"next_retry\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tnextRetry\x12\x19\n" +
	"\bbytes_in\x18\t \x01(\x03R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\n" +
	" \x01(\x03R\bbytesOut\x120\n" +
	"\x14effective_latency_ms\x18\v \x01(\x03R\x12effectiveLatencyMs\x12.\n" +
	"\x13effective_jitter_ms\x18\f \x01(\x03R\x11effectiveJitterMs\x12/\n" +
	"\x13effective_bandwidth\x18\r \x01(\x03R\x12effectiveBandwidth\x12#\n" +
	"\rchaos_enabled\x18\x0e \x01(\bR\fchaosEnabled\x12(\n" +
	"\x10chaos_error_rate\x18\x0f \x01(\x01R\x0echaosErrorRate\x126\n" +
	"\x17chaos_spike_probability\x18\x10 \x01(\x01R\x15chaosSpikeProbability\x125\n" +
	"\x17chaos_spike_duration_ms\x18\x11 \x01(\x03R\x14chaosSpikeDurationMs\x122\n" +
	"\x15chaos_errors_injected\x18\x12 \x01(\x03R\x13chaosErrorsInjected\x122\n" +
	"\x15chaos_spikes_injected\x18\x13 \x01(\x03R\x13chaosSpikesInjected\x12\"\n" +
	"\rconn_bytes_in\x18\x14 \x01(\x03R\vconnBytesIn\x12$\n" +
	"\x0econn_bytes_out\x18\x15 \x01(\x03R\fconnBytesOut\x12\x12\n" +
	"\x04lazy\x18\x16 \x01(\bR\x04lazy\x12\x1f\n" +
	"\vtunnel_open\x18\x17 \x01(\bR\n" +
	"tunnelOpen\"\x0f\n" +
	"\rStatusRequest\"\x9f\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12;\n" +
	"\bforwards\x18\x03 \x03(\v2\x1f.kubeport.v1.ForwardStatusProtoR\bforwards\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\r\n" +
	"\vStopRequest\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8e\x01\n" +
	"\x11AddServiceRequest\x122\n" +
	"\aservice\x18\x01 \x01(\v2\x18.kubeport.v1.ServiceInfoR\aservice\x12\x18\n" +
	"\apersist\x18\x02 \x01(\bR\apersist\x12+\n" +
	"\x05ports\x18\x03 \x01(\v2\x15.kubeport.v1.PortSpecR\x05ports\"\x88\x01\n" +
	"\x12AddServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vactual_port\x18\x03 \x01(\x05R\n" +
	"actualPort\x12!\n" +
	"\factual_ports\x18\x04 \x03(\x05R\vactualPorts\"D\n" +
	"\x14RemoveServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\apersist\x18\x02 \x01(\bR\apersist\"G\n" +
	"\x15RemoveServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x0f\n" +
	"\rReloadRequest\"p\n" +
	"\x0eReloadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x14\n" +
	"\x05added\x18\x03 \x01(\x05R\x05added\x12\x18\n" +
	"\aremoved\x18\x04 \x01(\x05R\aremoved\"Z\n" +
	"\fApplyRequest\x124\n" +
	"\bservices\x18\x01 \x03(\v2\x18.kubeport.v1.ServiceInfoR\bservices\x12\x14\n" +
	"\x05merge\x18\x02 \x01(\bR\x05merge\"\x8b\x01\n" +
	"\rApplyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x14\n" +
	"\x05added\x18\x03 \x01(\x05R\x05added\x12\x18\n" +
	"\askipped\x18\x04 \x01(\x05R\askipped\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\"w\n" +
	"\x0eAddressMapping\x12#\n" +
	"\rinternal_addr\x18\x01 \x01(\tR\finternalAddr\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x02 \x01(\tR\tlocalAddr\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\"\x8a\x02\n" +
	"\x12UpdateChaosRequest\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices\x120\n" +
	"\x06preset\x18\x02 \x01(\x0e2\x18.kubeport.v1.ChaosPresetR\x06preset\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x04 \x01(\x01R\terrorRate\x12+\n" +
	"\x11spike_probability\x18\x05 \x01(\x01R\x10spikeProbability\x12*\n" +
	"\x11spike_duration_ms\x18\x06 \x01(\x03R\x0fspikeDurationMs\x12\x14\n" +
	"\x05reset\x18\a \x01(\bR\x05reset\"L\n" +
	"\x13UpdateChaosResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x03(\tR\aupdated\x12\x1b\n" +
	"\tnot_found\x18\x02 \x03(\tR\bnotFound\"8\n" +
	"\x0fMappingsRequest\x12%\n" +
	"\x0ecluster_domain\x18\x01 \x01(\tR\rclusterDomain\"\xfd\x01\n" +
	"\x10MappingsResponse\x12>\n" +
	"\x05addrs\x18\x01 \x03(\v2(.kubeport.v1.MappingsResponse.AddrsEntryR\x05addrs\x127\n" +
	"\bmappings\x18\x02 \x03(\v2\x1b.kubeport.v1.AddressMappingR\bmappings\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x1a8\n" +
	"\n" +
	"AddrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xb4\x01\n" +
	"\fForwardState\x12\x1d\n" +
	"\x19FORWARD_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FORWARD_STATE_STARTING\x10\x01\x12\x19\n" +
	"\x15FORWARD_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14FORWARD_STATE_FAILED\x10\x03\x12\x19\n" +
	"\x15FORWARD_STATE_STOPPED\x10\x04\x12\x19\n" +
	"\x15FORWARD_STATE_WAITING\x10\x05*\x8b\x01\n" +
	"\vChaosPreset\x12\x1c\n" +
	"\x18CHAOS_PRESET_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CHAOS_PRESET_SLOW_NETWORK\x10\x01\x12!\n" +
	"\x1dCHAOS_PRESET_UNSTABLE_CLUSTER\x10\x02\x12\x1c\n" +
	"\x18CHAOS_PRESET_PACKET_LOSS\x10\x032\xd4\x04\n" +
	"\rDaemonService\x12A\n" +
	"\x06Status\x12\x1a.kubeport.v1.StatusRequest\x1a\x1b.kubeport.v1.StatusResponse\x12;\n" +
	"\x04Stop\x12\x18.kubeport.v1.StopRequest\x1a\x19.kubeport.v1.StopResponse\x12M\n" +
	"\n" +
	"AddService\x12\x1e.kubeport.v1.AddServiceRequest\x1a\x1f.kubeport.v1.AddServiceResponse\x12V\n" +
	"\rRemoveService\x12!.kubeport.v1.RemoveServiceRequest\x1a\".kubeport.v1.RemoveServiceResponse\x12A\n" +
	"\x06Reload\x12\x1a.kubeport.v1.ReloadRequest\x1a\x1b.kubeport.v1.ReloadResponse\x12>\n" +
	"\x05Apply\x12\x19.kubeport.v1.ApplyRequest\x1a\x1a.kubeport.v1.ApplyResponse\x12G\n" +
	"\bMappings\x12\x1c.kubeport.v1.MappingsRequest\x1a\x1d.kubeport.v1.MappingsResponse\x12P\n" +
	"\vUpdateChaos\x12\x1f.kubeport.v1.UpdateChaosRequest\x1a .kubeport.v1.UpdateChaosResponseB9Z7github.com/rbaliyan/kubeport/api/kubeport/v1;kubeportv1b\x06proto3"

var (
	file_kubeport_v1_daemon_proto_rawDescOnce sync.Once
	file_kubeport_v1_daemon_proto_rawDescData []byte
)

func file_kubeport_v1_daemon_proto_rawDescGZIP() []byte {
	file_kubeport_v1_daemon_proto_rawDescOnce.Do(func() {
		file_kubeport_v1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubeport_v1_daemon_proto_rawDesc), len(file_kubeport_v1_daemon_proto_rawDesc)))
	})
	return file_kubeport_v1_daemon_proto_rawDescData
}

var file_kubeport_v1_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kubeport_v1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_kubeport_v1_daemon_proto_goTypes = []any{
	(ForwardState)(0),             // 0: kubeport.v1.ForwardState
	(ChaosPreset)(0),              // 1: kubeport.v1.ChaosPreset
	(*ServiceInfo)(nil),           // 2: kubeport.v1.ServiceInfo
	(*PortSpec)(nil),              // 3: kubeport.v1.PortSpec
	(*ForwardStatusProto)(nil),    // 4: kubeport.v1.ForwardStatusProto
	(*StatusRequest)(nil),         // 5: kubeport.v1.StatusRequest
	(*StatusResponse)(nil),        // 6: kubeport.v1.StatusResponse
	(*StopRequest)(nil),           // 7: kubeport.v1.StopRequest
	(*StopResponse)(nil),          // 8: kubeport.v1.StopResponse
	(*AddServiceRequest)(nil),     // 9: kubeport.v1.AddServiceRequest
	(*AddServiceResponse)(nil),    // 10: kubeport.v1.AddServiceResponse
	(*RemoveServiceRequest)(nil),  // 11: kubeport.v1.RemoveServiceRequest
	(*RemoveServiceResponse)(nil), // 12: kubeport.v1.RemoveServiceResponse
	(*ReloadRequest)(nil),         // 13: kubeport.v1.ReloadRequest
	(*ReloadResponse)(nil),        // 14: kubeport.v1.ReloadResponse
	(*ApplyRequest)(nil),          // 15: kubeport.v1.ApplyRequest
	(*ApplyResponse)(nil),         // 16: kubeport.v1.ApplyResponse
	(*AddressMapping)(nil),        // 17: kubeport.v1.AddressMapping
	(*UpdateChaosRequest)(nil),    // 18: kubeport.v1.UpdateChaosRequest
	(*UpdateChaosResponse)(nil),   // 19: kubeport.v1.UpdateChaosResponse
	(*MappingsRequest)(nil),       // 20: kubeport.v1.MappingsRequest
	(*MappingsResponse)(nil),      // 21: kubeport.v1.MappingsResponse
	nil,                           // 22: kubeport.v1.MappingsResponse.AddrsEntry
	(*timestamppb.Timestamp)(nil), // 23: google.protobuf.Timestamp
}
var file_kubeport_v1_daemon_proto_depIdxs = []int32{
	2,  // 0: kubeport.v1.ForwardStatusProto.service:type_name -> kubeport.v1.ServiceInfo
	0,  // 1: kubeport.v1.ForwardStatusProto.state:type_name -> kubeport.v1.ForwardState
	23, // 2: kubeport.v1.ForwardStatusProto.last_start:type_name -> google.protobuf.Timestamp
	23, // 3: kubeport.v1.ForwardStatusProto.next_retry:type_name -> google.protobuf.Timestamp
	4,  // 4: kubeport.v1.StatusResponse.forwards:type_name -> kubeport.v1.ForwardStatusProto
	2,  // 5: kubeport.v1.AddServiceRequest.service:type_name -> kubeport.v1.ServiceInfo
	3,  // 6: kubeport.v1.AddServiceRequest.ports:type_name -> kubeport.v1.PortSpec
	2,  // 7: kubeport.v1.ApplyRequest.services:type_name -> kubeport.v1.ServiceInfo
	1,  // 8: kubeport.v1.UpdateChaosRequest.preset:type_name -> kubeport.v1.ChaosPreset
	22, // 9: kubeport.v1.MappingsResponse.addrs:type_name -> kubeport.v1.MappingsResponse.AddrsEntry
	17, // 10: kubeport.v1.MappingsResponse.mappings:type_name -> kubeport.v1.AddressMapping
	5,  // 11: kubeport.v1.DaemonService.Status:input_type -> kubeport.v1.StatusRequest
	7,  // 12: kubeport.v1.DaemonService.Stop:input_type -> kubeport.v1.StopRequest
	9,  // 13: kubeport.v1.DaemonService.AddService:input_type -> kubeport.v1.AddServiceRequest
	11, // 14: kubeport.v1.DaemonService.RemoveService:input_type -> kubeport.v1.RemoveServiceRequest
	13, // 15: kubeport.v1.DaemonService.Reload:input_type -> kubeport.v1.ReloadRequest
	15, // 16: kubeport.v1.DaemonService.Apply:input_type -> kubeport.v1.ApplyRequest
	20, // 17: kubeport.v1.DaemonService.Mappings:input_type -> kubeport.v1.MappingsRequest
	18, // 18: kubeport.v1.DaemonService.UpdateChaos:input_type -> kubeport.v1.UpdateChaosRequest
	6,  // 19: kubeport.v1.DaemonService.Status:output_type -> kubeport.v1.StatusResponse
	8,  // 20: kubeport.v1.DaemonService.Stop:output_type -> kubeport.v1.StopResponse
	10, // 21: kubeport.v1.DaemonService.AddService:output_type -> kubeport.v1.AddServiceResponse
	12, // 22: kubeport.v1.DaemonService.RemoveService:output_type -> kubeport.v1.RemoveServiceResponse
	14, // 23: kubeport.v1.DaemonService.Reload:output_type -> kubeport.v1.ReloadResponse
	16, // 24: kubeport.v1.DaemonService.Apply:output_type -> kubeport.v1.ApplyResponse
	21, // 25: kubeport.v1.DaemonService.Mappings:output_type -> kubeport.v1.MappingsResponse
	19, // 26: kubeport.v1.DaemonService.UpdateChaos:output_type -> kubeport.v1.UpdateChaosResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_kubeport_v1_daemon_proto_init() }
func file_kubeport_v1_daemon_proto_init() {
	if File_kubeport_v1_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubeport_v1_daemon_proto_rawDesc), len(file_kubeport_v1_daemon_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kubeport_v1_daemon_proto_goTypes,
		DependencyIndexes: file_kubeport_v1_daemon_proto_depIdxs,
		EnumInfos:         file_kubeport_v1_daemon_proto_enumTypes,
		MessageInfos:      file_kubeport_v1_daemon_proto_msgTypes,
	}.Build()
	File_kubeport_v1_daemon_proto = out.File
	file_kubeport_v1_daemon_proto_goTypes = nil
	file_kubeport_v1_daemon_proto_depIdxs = nil
}
