// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kubeport/v1/daemon.proto

package kubeportv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardState int32

const (
	ForwardState_FORWARD_STATE_UNSPECIFIED ForwardState = 0
	ForwardState_FORWARD_STATE_STARTING    ForwardState = 1
	ForwardState_FORWARD_STATE_RUNNING     ForwardState = 2
	ForwardState_FORWARD_STATE_FAILED      ForwardState = 3
	ForwardState_FORWARD_STATE_STOPPED     ForwardState = 4
)

// Enum value maps for ForwardState.
var (
	ForwardState_name = map[int32]string{
		0: "FORWARD_STATE_UNSPECIFIED",
		1: "FORWARD_STATE_STARTING",
		2: "FORWARD_STATE_RUNNING",
		3: "FORWARD_STATE_FAILED",
		4: "FORWARD_STATE_STOPPED",
	}
	ForwardState_value = map[string]int32{
		"FORWARD_STATE_UNSPECIFIED": 0,
		"FORWARD_STATE_STARTING":    1,
		"FORWARD_STATE_RUNNING":     2,
		"FORWARD_STATE_FAILED":      3,
		"FORWARD_STATE_STOPPED":     4,
	}
)

func (x ForwardState) Enum() *ForwardState {
	p := new(ForwardState)
	*p = x
	return p
}

func (x ForwardState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForwardState) Descriptor() protoreflect.EnumDescriptor {
	return file_kubeport_v1_daemon_proto_enumTypes[0].Descriptor()
}

func (ForwardState) Type() protoreflect.EnumType {
	return &file_kubeport_v1_daemon_proto_enumTypes[0]
}

func (x ForwardState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForwardState.Descriptor instead.
func (ForwardState) EnumDescriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{0}
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Pod           string                 `protobuf:"bytes,3,opt,name=pod,proto3" json:"pod,omitempty"`
	LocalPort     int32                  `protobuf:"varint,4,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RemotePort    int32                  `protobuf:"varint,5,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	Namespace     string                 `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ServiceInfo) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *ServiceInfo) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *ServiceInfo) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *ServiceInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ForwardStatusProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceInfo           `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	State         ForwardState           `protobuf:"varint,2,opt,name=state,proto3,enum=kubeport.v1.ForwardState" json:"state,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Restarts      int32                  `protobuf:"varint,4,opt,name=restarts,proto3" json:"restarts,omitempty"`
	LastStart     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_start,json=lastStart,proto3" json:"last_start,omitempty"`
	Connected     bool                   `protobuf:"varint,6,opt,name=connected,proto3" json:"connected,omitempty"`
	ActualPort    int32                  `protobuf:"varint,7,opt,name=actual_port,json=actualPort,proto3" json:"actual_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardStatusProto) Reset() {
	*x = ForwardStatusProto{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardStatusProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardStatusProto) ProtoMessage() {}

func (x *ForwardStatusProto) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardStatusProto.ProtoReflect.Descriptor instead.
func (*ForwardStatusProto) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardStatusProto) GetService() *ServiceInfo {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ForwardStatusProto) GetState() ForwardState {
	if x != nil {
		return x.State
	}
	return ForwardState_FORWARD_STATE_UNSPECIFIED
}

func (x *ForwardStatusProto) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ForwardStatusProto) GetRestarts() int32 {
	if x != nil {
		return x.Restarts
	}
	return 0
}

func (x *ForwardStatusProto) GetLastStart() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStart
	}
	return nil
}

func (x *ForwardStatusProto) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *ForwardStatusProto) GetActualPort() int32 {
	if x != nil {
		return x.ActualPort
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{2}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Forwards      []*ForwardStatusProto  `protobuf:"bytes,3,rep,name=forwards,proto3" json:"forwards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *StatusResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *StatusResponse) GetForwards() []*ForwardStatusProto {
	if x != nil {
		return x.Forwards
	}
	return nil
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{4}
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_kubeport_v1_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubeport_v1_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_kubeport_v1_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_kubeport_v1_daemon_proto protoreflect.FileDescriptor

const file_kubeport_v1_daemon_proto_rawDesc = "" +
	"\n" +
	"\x18kubeport/v1/daemon.proto\x12\vkubeport.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x01\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x10\n" +
	"\x03pod\x18\x03 \x01(\tR\x03pod\x12\x1d\n" +
	"\n" +
	"local_port\x18\x04 \x01(\x05R\tlocalPort\x12\x1f\n" +
	"\vremote_port\x18\x05 \x01(\x05R\n" +
	"remotePort\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\"\xa5\x02\n" +
	"\x12ForwardStatusProto\x122\n" +
	"\aservice\x18\x01 \x01(\v2\x18.kubeport.v1.ServiceInfoR\aservice\x12/\n" +
	"\x05state\x18\x02 \x01(\x0e2\x19.kubeport.v1.ForwardStateR\x05state\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1a\n" +
	"\brestarts\x18\x04 \x01(\x05R\brestarts\x129\n" +
	"\n" +
	"last_start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tlastStart\x12\x1c\n" +
	"\tconnected\x18\x06 \x01(\bR\tconnected\x12\x1f\n" +
	"\vactual_port\x18\a \x01(\x05R\n" +
	"actualPort\"\x0f\n" +
	"\rStatusRequest\"\x85\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12;\n" +
	"\bforwards\x18\x03 \x03(\v2\x1f.kubeport.v1.ForwardStatusProtoR\bforwards\"\r\n" +
	"\vStopRequest\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\x99\x01\n" +
	"\fForwardState\x12\x1d\n" +
	"\x19FORWARD_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FORWARD_STATE_STARTING\x10\x01\x12\x19\n" +
	"\x15FORWARD_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14FORWARD_STATE_FAILED\x10\x03\x12\x19\n" +
	"\x15FORWARD_STATE_STOPPED\x10\x042\x8f\x01\n" +
	"\rDaemonService\x12A\n" +
	"\x06Status\x12\x1a.kubeport.v1.StatusRequest\x1a\x1b.kubeport.v1.StatusResponse\x12;\n" +
	"\x04Stop\x12\x18.kubeport.v1.StopRequest\x1a\x19.kubeport.v1.StopResponseB9Z7github.com/rbaliyan/kubeport/api/kubeport/v1;kubeportv1b\x06proto3"

var (
	file_kubeport_v1_daemon_proto_rawDescOnce sync.Once
	file_kubeport_v1_daemon_proto_rawDescData []byte
)

func file_kubeport_v1_daemon_proto_rawDescGZIP() []byte {
	file_kubeport_v1_daemon_proto_rawDescOnce.Do(func() {
		file_kubeport_v1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubeport_v1_daemon_proto_rawDesc), len(file_kubeport_v1_daemon_proto_rawDesc)))
	})
	return file_kubeport_v1_daemon_proto_rawDescData
}

var file_kubeport_v1_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kubeport_v1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_kubeport_v1_daemon_proto_goTypes = []any{
	(ForwardState)(0),             // 0: kubeport.v1.ForwardState
	(*ServiceInfo)(nil),           // 1: kubeport.v1.ServiceInfo
	(*ForwardStatusProto)(nil),    // 2: kubeport.v1.ForwardStatusProto
	(*StatusRequest)(nil),         // 3: kubeport.v1.StatusRequest
	(*StatusResponse)(nil),        // 4: kubeport.v1.StatusResponse
	(*StopRequest)(nil),           // 5: kubeport.v1.StopRequest
	(*StopResponse)(nil),          // 6: kubeport.v1.StopResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_kubeport_v1_daemon_proto_depIdxs = []int32{
	1, // 0: kubeport.v1.ForwardStatusProto.service:type_name -> kubeport.v1.ServiceInfo
	0, // 1: kubeport.v1.ForwardStatusProto.state:type_name -> kubeport.v1.ForwardState
	7, // 2: kubeport.v1.ForwardStatusProto.last_start:type_name -> google.protobuf.Timestamp
	2, // 3: kubeport.v1.StatusResponse.forwards:type_name -> kubeport.v1.ForwardStatusProto
	3, // 4: kubeport.v1.DaemonService.Status:input_type -> kubeport.v1.StatusRequest
	5, // 5: kubeport.v1.DaemonService.Stop:input_type -> kubeport.v1.StopRequest
	4, // 6: kubeport.v1.DaemonService.Status:output_type -> kubeport.v1.StatusResponse
	6, // 7: kubeport.v1.DaemonService.Stop:output_type -> kubeport.v1.StopResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_kubeport_v1_daemon_proto_init() }
func file_kubeport_v1_daemon_proto_init() {
	if File_kubeport_v1_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubeport_v1_daemon_proto_rawDesc), len(file_kubeport_v1_daemon_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kubeport_v1_daemon_proto_goTypes,
		DependencyIndexes: file_kubeport_v1_daemon_proto_depIdxs,
		EnumInfos:         file_kubeport_v1_daemon_proto_enumTypes,
		MessageInfos:      file_kubeport_v1_daemon_proto_msgTypes,
	}.Build()
	File_kubeport_v1_daemon_proto = out.File
	file_kubeport_v1_daemon_proto_goTypes = nil
	file_kubeport_v1_daemon_proto_depIdxs = nil
}
